# Autogenerated wrapper script for Woff2_jll for i686-w64-mingw32-cxx03
export libwoff2common, libwoff2dec, libwoff2enc

using brotli_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Woff2")
JLLWrappers.@declare_library_product(libwoff2common, "libwoff2common.dll")
JLLWrappers.@declare_library_product(libwoff2dec, "libwoff2dec.dll")
JLLWrappers.@declare_library_product(libwoff2enc, "libwoff2enc.dll")
function __init__()
    JLLWrappers.@generate_init_header(brotli_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libwoff2common,
        "bin\\libwoff2common.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libwoff2dec,
        "bin\\libwoff2dec.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libwoff2enc,
        "bin\\libwoff2enc.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
