# Autogenerated wrapper script for Woff2_jll for x86_64-apple-darwin
export libwoff2common, libwoff2dec, libwoff2enc

using brotli_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Woff2")
JLLWrappers.@declare_library_product(libwoff2common, "@rpath/libwoff2common.1.0.2.dylib")
JLLWrappers.@declare_library_product(libwoff2dec, "@rpath/libwoff2dec.1.0.2.dylib")
JLLWrappers.@declare_library_product(libwoff2enc, "@rpath/libwoff2enc.1.0.2.dylib")
function __init__()
    JLLWrappers.@generate_init_header(brotli_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libwoff2common,
        "lib/libwoff2common.1.0.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libwoff2dec,
        "lib/libwoff2dec.1.0.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libwoff2enc,
        "lib/libwoff2enc.1.0.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
